runtime: python311

instance_class: F1

env_variables:
  DEPLOYED: True

service_account: flow-universal@ak-flow.iam.gserviceaccount.com
handlers:
- url: /static
  static_dir: static/

- url: /.*
  secure: always
  redirect_http_response_code: 301
  script: auto