# Generated by Django 5.0 on 2023-12-12 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=50, null=True)),
                ('last_name', models.CharField(blank=True, max_length=50, null=True)),
                ('gender', models.CharField(blank=True, max_length=10, null=True)),
                ('age', models.DecimalField(blank=True, decimal_places=0, max_digits=7, null=True)),
                ('major', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
