# Generated by Django 5.0.1 on 2024-01-09 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_review_difficulty_review_useful'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='schools/'),
        ),
    ]
