# Generated by Django 4.1 on 2023-12-24 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_review'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
