# Generated by Django 5.0.1 on 2024-01-14 01:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_course_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='useful',
            new_name='utility',
        ),
    ]
