# Generated by Django 4.1 on 2023-12-24 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='description',
        ),
        migrations.AddField(
            model_name='review',
            name='anonymous',
            field=models.BooleanField(default=False),
        ),
    ]
