# Generated by Django 4.1 on 2023-12-24 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_remove_department_description_review_anonymous'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='emails',
            new_name='email',
        ),
    ]
