name: Deploy to GAE

on:
  workflow_dispatch:

jobs:
  deploy:
    name: Deploying to Google Cloud
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v4
          with:
            lfs: true
        - name: Checkout LFS objects
          run: git lfs checkout

        - uses: actions/setup-python@v4
          with:
              python-version: '3.11'             

        - name: Install Requirements
          run: |
              pip install -r requirements.txt

        - name: Gather Static Files
          run: |
              python manage.py collectstatic --noinput

        - name: Run Migrations
          run: |
              python manage.py makemigrations
              python manage.py migrate

        - name: Authorize Gcloud
          uses: google-github-actions/auth@v2
          with:
            project_id: ${{ secrets.PROJECT_ID }}
            credentials_json: ${{ secrets.SERVICE_ACCOUNT }}

        - name: Connect to gcloud
          uses: google-github-actions/setup-gcloud@v2

        - name: Deploy to App Engine
          uses: google-github-actions/deploy-appengine@v2
          with:
            project_id: ${{ secrets.PROJECT_ID }}
            deliverables: |
              app.yaml
